/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Test
 */
export type PeersPeersItem = {
  id?: string
  address?: string
  parcel?: number[]
  position?: number[]
  lastPing?: number
}

export interface Peers {
  ok?: boolean
  peers?: PeersPeersItem[]
}

export type Ok = PeersOk

export type Schema = Peers
