/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Test
 */
import axios from 'axios'
import type { AxiosRequestConfig, AxiosResponse } from 'axios'
import type { Peers } from './client.schemas'

/**
 * Retrieves the list peers in the server with details about their positions and islands.
 * @summary List of peers
 */
export const getPeers = <TData = AxiosResponse<Peers>>(options?: AxiosRequestConfig): Promise<TData> => {
  return axios.get(`/comms/peers`, options)
}

export type GetPeersResult = AxiosResponse<Peers>
